export const itemsActions = {
    ITEMS_HAS_ERRORED: "ITEMS_HAS_ERRORED",
    ITEMS_IS_LOADING: "ITEMS_IS_LOADING",
    ITEMS_FETCH_DATA_SUCCESS: "ITEMS_FETCH_DATA_SUCCESS"
}

export const itemActions = {
    ITEM_HAS_ERRORED: "ITEM_HAS_ERRORED",
    ITEM_IS_LOADING: "ITEM_IS_LOADING",
    ITEM_FETCH_DATA_SUCCESS: "ITEM_FETCH_DATA_SUCCESS"
}
